### ISSUE TITLE
Milestone 2 Feedback 

### ISSUE THREAD

**Issue by bcheggeseth** [yospepin/welovemaps_project#1]
**Requested File Structure**
- [x] code
- [x] data
- [x] planning with Milestone1.qmd  

**.gitignore**
- [x] Created a .gitignore file
- [x] Contains all of the request files in it

**Milestone2.qmd**
- [x] Progress on the stated plan
- I recommend taking your code for data cleaning and putting it in an R Script file called Cleaning.R so that you can source('Cleaning.R') from another file if you need to. Also, you can save the clean data file.
- Your work is in the qmd but you didn't render the qmd (and the data files are on Github, generally for a good reason) so I can't see your work in html format. Please ensure that you've render to create the html.
- [x] Future plan for Milestone 3
- [x] Included sessionInfo() at the end of qmd files

General Feedback:

- I highly recommend getting county-level demographic information from tidycensus to supplement what you've found. It has the spatial geometries and can deepen your investigation and your data story. 
- As you explore these changes, you'll need to provide context of the purchasing power of a  dollar. Even if incomes to increase, does that mean families are better off? 

Collaboration:

- I will check commits every Milestone to ensure everyone is contributing through Git commits.
- It seems like you all made contributions to this milestone.
