### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by lsokolew** [yospepin/welovemaps_project#2]
Milestone 3 Feedback

**Requested File Structure**
- [x] results folder 
- [x] with Milestone3-Blog.qmd 
- [x] with rendered html
- [ ] Included sessionInfo() at the end of qmd files
- only in other milestone qmds

**Progress from Milestone 2**
- [x] Progress on the stated plan

**Milestone3-Blog**
images aren’t appearing in your HTML; try adding `embed-resources: true` to your qmd
- [ ] < 1000 words
- ~1100, excluding code
- [x] Motivate the importance of the topic
- [x] Lead the reader through the rationale for the narrowing/focusing of the scope via the main 2-3 broad questions
- [x] Tie results (plots and modeling output) to the broad questions and explain how all results fit together
- [x] End with main takeaways, limitations with regard to the data context and ethical considerations, and future directions
