### ISSUE TITLE
Milestone 5: Planning

### ISSUE THREAD

**Issue by yospepin** [yospepin/welovemaps_project#4]
Plan for the rest of the project:

Yosephine:
- [ ] Modify the new data with inflation rate considered to match the original data so we can use them for the Shiny App
- [ ] Refine the Shiny App --> add tabs, try to make a tract level analysis for the urban areas to have better understanding of our initial research question

Ellie:
- [ ] Figure out if we can make a slider for the map that shows the progression of the income over the years
- [ ] Working on the write up

Iris:
- [ ] Also making a slider for the map that shows income over years
- [ ] Making a tract-level analysis using census tract for the urban areas
